import "./globals.css";

import type { Metadata } from "next";

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Lista de Pagantes | REG Tropuê ❤️💛",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`font-["Outfit"] antialiased`}>{children}</body>
    </html>
  );
}
